---

- hosts: localhost
  vars:
    nios_provider:
      host: 192.168.1.10
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: Create Nios A record Test
     infoblox.nios_modules.nios_a_record:
       name: testansible.bau.com.mx
       view: Externa
       ipv4: 192.168.1.250
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
